services:
  nginx:
    container_name: ex2_nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    networks:
      - ex2_network
  php:
    container_name: ex2_php
    restart: unless-stopped
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd
    networks:
     - ex2_network
networks:
  ex2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.1.0/24




